version: '3.8'

services:
  ghost:
    image: ${GHOST_IMAGE:-ghost:5-alpine}
    ports:
      - "2368:2368"
    environment:
      - url=http://localhost:2368
    depends_on:
      - mysql

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}